### ISSUE TITLE
bower install waits for input

### ISSUE THREAD

**Issue by JedMeister** [kefniark/turnkey-laravel#1]
[Ln 66 in conf.d/main](https://github.com/kefniark/turnkey-laravel/blob/master/conf.d/main#L66) waits for input.

A bit of a google suggests that it should use `--config.interactive=false` to install silently.

**Comment by kefniark** [comment]
Thanks, I just fix it

**Comment by JedMeister** [comment]
Nice work! Quick fix! :)
